### ISSUE TITLE
can render_scene_view tool use on TMZ2 or TMZ3?

### ISSUE THREAD

**Issue by knuckleslee** [koolkdev/rsdkv5_extract#6]
It displays an error message
construct.core.FieldError: could not read enough bytes, expected 576, found 512
    (parsing) -> Views -> items -> some_array -> compressed_data
Failed to execute script render_scene_view

**Comment by RagdollClash** [comment]
i get the following when using the latest version on both stages:
```
Traceback (most recent call last):
  File "render_scene_view.py", line 15, in <module>
  File "site-packages\construct\core.py", line 161, in parse
  File "site-packages\construct\core.py", line 174, in parse_stream
  File "site-packages\construct\core.py", line 844, in _parse
  File "site-packages\construct\core.py", line 2705, in _parse
  File "site-packages\construct\core.py", line 3063, in _parse
  File "site-packages\construct\core.py", line 2709, in _parse
construct.core.RangeError: expected 5 to 5, found 0
    (parsing) -> Views -> items
Failed to execute script render_scene_view
```

**Comment by koolkdev** [comment]
fixed  (in the python, not in the exe yet). 
That background is scrolling vertically, so the scrolling array size should be by the width and not by height.
